using ContaCorrente.Data;
using ContaCorrente.Domain;
using ContaCorrenteServices.Interfaces;

namespace ContaCorrenteServices
{
    public class SeedService : ISeedService
    {
        private readonly ExtratoContext _context;

        public SeedService(ExtratoContext context)
        {
            _context = context;
        }
        public async Task Seed()
        {
            var extratos = new List<Extrato> 
            {
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-2), Avulso = false, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-2), Avulso = false, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-2), Avulso = false, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-2), Avulso = false, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-2), Avulso = false, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-2), Avulso = false, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-2), Avulso = false, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-1), Avulso = false, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-1), Avulso = false, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-1), Avulso = false, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-1), Avulso = false, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-1), Avulso = false, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-1), Avulso = false, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-1), Avulso = false, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-1), Avulso = false, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-1), Avulso = false, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-1), Avulso = false, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-3), Avulso = false, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-3), Avulso = false, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-3), Avulso = false, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-3), Avulso = false, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-3), Avulso = false, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-3), Avulso = false, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-3), Avulso = false, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-3), Avulso = false, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-3), Avulso = false, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(1), Avulso = false, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(1), Avulso = false, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(1), Avulso = false, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(1), Avulso = false, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(1), Avulso = false, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(1), Avulso = false, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(1), Avulso = false, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(1), Avulso = false, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-2), Avulso = false, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-2), Avulso = false, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-2), Avulso = false, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-2), Avulso = false, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-2), Avulso = false, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-2), Avulso = false, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-2), Avulso = false, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-1), Avulso = false, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-1), Avulso = false, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-1), Avulso = false, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-1), Avulso = false, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-1), Avulso = false, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-1), Avulso = false, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-1), Avulso = false, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-1), Avulso = false, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-1), Avulso = false, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-1), Avulso = false, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-3), Avulso = false, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-3), Avulso = false, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-3), Avulso = false, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-3), Avulso = false, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-3), Avulso = false, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-3), Avulso = false, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-3), Avulso = false, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-3), Avulso = false, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-3), Avulso = false, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(1), Avulso = false, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(1), Avulso = false, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(1), Avulso = false, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(1), Avulso = false, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(1), Avulso = false, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(1), Avulso = false, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(1), Avulso = false, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(1), Avulso = false, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-2), Avulso = true, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-2), Avulso = true, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-2), Avulso = true, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-2), Avulso = true, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-2), Avulso = true, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-2), Avulso = true, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-2), Avulso = true, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-1), Avulso = true, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-1), Avulso = true, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-1), Avulso = true, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-1), Avulso = true, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-1), Avulso = true, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-1), Avulso = true, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-1), Avulso = true, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-1), Avulso = true, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-1), Avulso = true, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-1), Avulso = true, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-3), Avulso = true, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-3), Avulso = true, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-3), Avulso = true, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-3), Avulso = true, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-3), Avulso = true, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-3), Avulso = true, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-3), Avulso = true, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-3), Avulso = true, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-3), Avulso = true, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(1), Avulso = true, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(1), Avulso = true, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(1), Avulso = true, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(1), Avulso = true, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(1), Avulso = true, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(1), Avulso = true, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(1), Avulso = true, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(1), Avulso = true, Status = "Cancelado" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-2), Avulso = true, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-2), Avulso = true, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-2), Avulso = true, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-2), Avulso = true, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-2), Avulso = true, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-2), Avulso = true, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-2), Avulso = true, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-1), Avulso = true, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-1), Avulso = true, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-1), Avulso = true, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-1), Avulso = true, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-1), Avulso = true, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-1), Avulso = true, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-1), Avulso = true, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-1), Avulso = true, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-1), Avulso = true, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-1), Avulso = true, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-3), Avulso = true, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-3), Avulso = true, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-3), Avulso = true, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-3), Avulso = true, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-3), Avulso = true, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-3), Avulso = true, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-3), Avulso = true, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-3), Avulso = true, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(-3), Avulso = true, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(1), Avulso = true, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(1), Avulso = true, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(1), Avulso = true, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(1), Avulso = true, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(1), Avulso = true, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(1), Avulso = true, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(1), Avulso = true, Status = "Válido" },
                new Extrato { Id = Guid.NewGuid(), Valor = 10M, Descricao = "Transferência recebida", Data = DateTime.Now.AddDays(1), Avulso = true, Status = "Válido" }
            };
            Random rdn = new Random();
            foreach (var e in extratos)
            {
                e.Valor += rdn.Next(10, 100);
            }

            await _context.AddRangeAsync(extratos);
            await _context.SaveChangesAsync();
        }

    }
}